### ISSUE TITLE
BrandBand background images 404 in production use

### ISSUE THREAD

**Issue by extronics** [propertybase/react-lds#302] opened 2018-03-21 14:16 UTC
The background image urls come straight from the CSS and therefore ignore the `sldsAssetRoot` setting. When using the react-lds as a static resource in SF, the background images 404 because of this.

**Comment by fspoettel** [comment] 2018-03-23 10:50
Not a bug on our side, this needs to be fixed upstream

**Comment by fspoettel** [comment] 2018-03-23 11:04
Tracking in https://github.com/salesforce-ux/design-system/issues/539

**Comment by fspoettel** [comment] 2018-03-29 15:29
Will be fixed with move to `<apex:slds />` for us, so this problem will only affect our docs for now.

**Closed** 2018-11-14 11:12 UTC
Labels: Status: Blocked, Type: Bug
